version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: aifm-postgres
    environment:
      POSTGRES_DB: aifm_dev
      POSTGRES_USER: aifm
      POSTGRES_PASSWORD: aifm_dev_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aifm"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (for BullMQ queues)
  redis:
    image: redis:7-alpine
    container_name: aifm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
